### ISSUE TITLE
Crash Fix

### ISSUE THREAD

**Issue by honeycoder96** [DSC-Galgotias/TechnoJam-Chat#38]
#### Logcat Message
>  --------- beginning of crash
10-24 13:30:44.537 19746-19746/tech.honeysharma.techbmechat E/AndroidRuntime: FATAL EXCEPTION: main
    Process: tech.honeysharma.techbmechat, PID: 19746
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
        at tech.honeysharma.techbmechat.Account.SettingsActivity.setUserData(SettingsActivity.java:332)
        at tech.honeysharma.techbmechat.Account.SettingsActivity.access$000(SettingsActivity.java:47)
        at tech.honeysharma.techbmechat.Account.SettingsActivity$1.onDataChange(SettingsActivity.java:108)
        at com.google.android.gms.internal.zzegf.zza(Unknown Source)
        at com.google.android.gms.internal.zzeia.zzbyc(Unknown Source)
        at com.google.android.gms.internal.zzeig.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:742)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5604)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)

## Fix the crash by removing null pointer exception.

**Comment by mohak1283** [comment]
Where the error is coming in which Activity @honeycoder96

**Comment by mohak1283** [comment]
@honeycoder96 It's working fine on my device.
I clicked on Account Settings option from overflow menu and AccounSettingActivity opens without any crash

**Comment by honeycoder96** [comment]
Turns out a minor fault associated with the account.
Its been fixed.
